"""change the data type of column of chats_agent table

Revision ID: a485ac392c4a
Revises: 5bd33b829f90
Create Date: 2026-09-21 12:52:31.513350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a485ac392c4a'
down_revision: Union[str, Sequence[str], None] = '5bd33b829f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats_agent', 'content',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='content::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats_agent', 'content',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False,
               postgresql_using='content::text')
    # ### end Alembic commands ###
